### ISSUE TITLE
Create Spreadsheet to track NTD Data Requests from RTPA

### ISSUE THREAD

**Issue by shweta487** [cal-itp/data-analyses#1057]
## Create Spreadsheet to Track NTD Data Requests from RTPA

We need to create a spreadsheet to track the NTD data requests from RTPA (Regional Transportation Planning Agencies). The spreadsheet will help us organize and manage the requests effectively. 

The spreadsheet should include columns for 
- Requested NTD data
- Contact information of the requester
- Email address of the requester
- Names of relevant annual reporters requested by RTPA

**Comment by csuyat-dot** [comment]
Spreadsheet started, can be found in [Teams/Sharepoint](https://caltrans.sharepoint.com/:x:/s/DOTPMPHQ-DataandDigitalServices/EV3dx9mQOixPlXVgnyP0sHkB1TueA3Z_Lp-d9TCiaPVYTQ?e=mGzXaX)
