### ISSUE TITLE
Research Task - SB125 Allocation Package Data Cleaning

### ISSUE THREAD

**Issue by csuyat-dot** [cal-itp/data-analyses#1097]
## Research Task

Use this template to create issues that represent small chunks of work (.5 - 2 days) that stand alone, or represent incremental work as part of an [Epic Issue Template](https://github.com/cal-itp/data-analyses/issues/new?assignees=&labels=epic&template=epic.md&title=Epic+-+%5BResearch+Request+Project+Title%5D).

* **Relevant PR** (if applicable):  

* **Question or Goal**: RTPAs/Orgs submitted allocation packages for SB125 funding, do these packages meet all the requirements per the SB125 final guidelines?

* **Data Required**:
  * Currently have: [submitted SB125 allocation packages](https://caltrans.sharepoint.com/:f:/s/DOTPMPHQ-DataandDigitalServices/EsBnuNhOsdFLuGoW9pE88qcBIMpu61I8bWL0DKjbSHf-ZA?e=HxwzP3), [allocation packages submitted via Google Survey](https://caltrans.sharepoint.com/:x:/s/DOTPMPHQ-DataandDigitalServices/EXmERr9Od8hFuDouk31dB_4B-37Xv3c90cR2R2q1v0vx1w?e=lJ16vr), [SB125 final guideline](https://calsta.ca.gov/-/media/calsta-media/documents/sb125-final-guidelines-a11y.pdf), 
  * Need:  

* **Research Required**:  Read SB125 final guideline to understand context of what is submitted. 

* **Metrics**: a yes/no value for the presence of each requirement   

* **Expected Outputs / Findings**: A table where each row is a RTPA/Org, columns of each requirements for allocation packages and yes/no values to indicate if the RTPA met the specific requirement.

**Comment by csuyat-dot** [comment]
**Initial work plan**
- Start an excel file in SB125 folder in Teams, layout rows/columns per above. May need to use the same layout as the google survey
- Enter the RTPA/org name of each submitted allocation package into the sheet
- For each package, mark whether each requirements is met

**Future work plan**
- add pdf allocation package data to google survey to fill in gaps,
- explore what analyses and metrics can be done with all this data

**Comment by csuyat-dot** [comment]
[Observation note ](https://caltrans.sharepoint.com/:w:/s/DOTPMPHQ-DataandDigitalServices/ESkML-whvPdDuT7JenqdjHwBQ_Udz5Mgxm8nYdCAx8b_OA?e=XYxLqs)
[Slide Deck](https://caltrans.sharepoint.com/:p:/s/DOTPMPHQ-DataandDigitalServices/ERFqejcW15dPnZohwSoryPQBomM9lxJxhtqZ4HSNb8Hhhg?e=qCBfPI)

**Comment by edasmalchi** [comment]
meeting w/ Anthony Serna and maybe Chad soon for next steps from CalSTA

**Comment by edasmalchi** [comment]
closing since initial scope complete, may create future issue if needed
