### ISSUE TITLE
Research Request - TTTF Route-level Illustrative Examples

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#1098]
# Research Question

What might accessibility and travel times look like for several illustrative trip examples around the state?

Required metrics:

- Auto travel time and reliability (_fastest/best auto route, no need to follow transit route_)
- Transit travel time, transfers, and span of service (possibly reliability too)

## Napa

* [Napa High School to Vallejo Ferry Terminal](https://maps.app.goo.gl/Qqor9KV9BQLmbgtd8)
- [x] Transit
- [x] Auto

	
## Sacramento

* [P St/22nd St to 5248 Rose St](https://maps.app.goo.gl/4KkDxReJyKUenMXU6)
- [x] Transit
- [x] Auto

## Clovis (existing and redesigned transit networks)

* [9248 N Laureen Ave to Clovis Community Hospital](https://maps.app.goo.gl/mF3euc16ycxpJfFN6)
- [x] Transit
- [x] Auto

## LA

* [Slauson/5th to Burbank Town Center Mall](https://maps.app.goo.gl/BsjkU3sVFg3A1Viy6)
- [x] Transit
- [x] Auto

## Solano

* [Vallejo Ferry Terminal to Solano Community College Vallejo](https://maps.app.goo.gl/FkDTbYY3xh4oCGmX9)
- [x] Transit
- [x] Auto

## Data sources

Conveyal, GTFS Warehouse, Streetlight

## Deliverables

Metrics, presentation TBD with TTTF consultants

## Timeline of deliverables
May 17?

**Comment by noah-ca** [comment]
@edasmalchi Is there a folder in GCS where we are storing the data for this issue?

**Comment by edasmalchi** [comment]
@noah-ca let's use this one : `calitp-analytics-data/data-analyses/sb125/route_illustrations`

**Comment by noah-ca** [comment]
> @noah-ca let's use this one : `calitp-analytics-data/data-analyses/sb125/route_illustrations`

Sounds good.

**Comment by edasmalchi** [comment]
yep no worries!
