### ISSUE TITLE
Research Request - Speedmap segments for GTFS analytics monthly pipeline 

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#1109]
Complete the below when receiving a research request, and continue to add to this issue as you receive additional details and produce deliverables. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

## Research Question
**Single sentence** description: Work speedmap segments (1,000 meters) into the same nearest neighbor pipeline as stop segments.
* Fold in the work done in these 2 PRs 
   * #1084
   * #1086  
* Test a single date, look at results in a map
* Make sure this part of the pipeline works seamlessly in a monthly run
* Backfill the previous dates

## Deliverables
- [x] add speedmap variables into `gtfs_analytics_data.yml`
- [x] similar to how `stop_segments` and `rt_stop_times` are set up, we need a `pipe_speedmap.py` script
- [x] add an averaging script that gets the processed data for mapping
- [ ] edit existing Mermaid diagram to include speedmaps

**Comment by tiffanychu90** [comment]
@edasmalchi: Can you take a look at [this trip-segment speeds](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_analytics_data.yml#L106) dataset and [these datasets that have been averaged](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_analytics_data.yml#L111-L112). Available dates are `rt_dates.DATES["mar2024"]` or `rt_dates.DATES["apr2024"]`

**Comment by edasmalchi** [comment]
@tiffanychu90 yes! will dig into it starting Tuesday. Thanks for your work on this 🙂
