### ISSUE TITLE
Docs: Portfolio Clarifications

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#1138]
*Reference*: [docs.calitp.org/data-infra/](https://docs.calitp.org/data-infra/)

**What type of changes need to be made?**
Select all that apply
- [ ] Edits
- [ ] Additions

**Describe the changes**
https://docs.calitp.org/data-infra/publishing/sections/5_notebooks_styling.html
https://docs.calitp.org/data-infra/publishing/sections/4_analytics_portfolio_site.html

Make these sections easier to follow, including without requiring reference to external links where possible. Link/integrate example notebook content in `starter_kit`

Some specifics:

- Clarify that page titles come from notebook H1, not yml
- May need to create a local index dir, if running index (also describe why/when to do this, consider tweaking script)

**Files Affected**:
List the files added or edited by these changes.
Ex.
* `Introduction to Analytics Tools`/`Notebooks`

**Additional context**
Add any other context.
#1122

**Comment by edasmalchi** [comment]
index command to document: https://github.com/cal-itp/data-analyses/pull/977

**Comment by amandaha8** [comment]
1. Clarify that page titles come from notebook H1, not yml
-SB125_route_illustrations.yml
-You might assume that page titles are from YML
-Titles in our website come from the headers of a notebook.
-Portfolio Script is taking something from the notebook and using it to build a table of contents.
-H1 is the boldest header.
2. May need to create a local index dir, if running index (also describe why/when to do this, consider tweaking script)
-There’s a second command to run that will build that index page
-PR #977 has details.

3. Cal-ITP Analytics Portfolio: dla.yml
Add more districts as an example to showcase how parameterization is happening 

4. Eric will expand on this page on Cal-ITP Analytics Portfolio
5. Swap order of the pages: notebooks_styling and analytics_portfolio. Styling the notebook should come before building your YML/parameterizing/etc.
6. Put deploy back to the analytics_portfolio
7. Do a PR and Eric will add his stuff.

**Comment by amandaha8** [comment]
Closed, all changes are merged into [d](https://docs.calitp.org/data-infra/intro.html)
