### ISSUE TITLE
Feature Request: NTD Data Demonstration Charts in Metabase

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-analyses#1150]
**Where does your feature apply?**

- [x] Data (the warehouse)
- [ ] JupyterHub
- [x] Metabase
- [ ] analysis.calitp.org  
- [ ] Other (add detail)

**Is your feature request related to a problem? Please describe.**

Create a few queries that can be added to the [Transit Agency Profile Dashboard](https://dashboards.calitp.org/dashboard/184-transit-agency-profile-dashboard?tab=15-overview&text=Amtrak) in the NTD tab to demonstrate querying and usage of NTD data.

**Describe the solution you'd like**

Number stats
- 2022 Annual ridership
- 2022 Annual VOMS

Line charts with monthly data
- UPT
- VRM
- VRH
- VOMS

**Describe alternatives you've considered**

Scraping data manually and using notebooks.

**Additional context**

A continuation of the work in https://github.com/cal-itp/data-infra/issues/3164

**Comment by vevetron** [comment]
Need to add a dim table with ntd mode -> description of mode.

**Comment by vevetron** [comment]
> Need to add a dim table with ntd mode -> description of mode.

That was solved in https://github.com/cal-itp/data-infra/pull/3386

**Comment by evansiroky** [comment]
Confirmed that this is complete. Thanks @vevetron!
