### ISSUE TITLE
Bug: some missing operators in SHS Stops Export

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#1216]
Uriel noticed that the export from #1160 didn't include SBMTD and would like to have those stops included so that he has as close to a complete census of stops along the SHS as possible.

Long Beach and B-Line are also not included due to [#3383](https://github.com/cal-itp/data-infra/issues/3383).

~~SBMTD is present in the warehouse for Aug 14 but apparently didn't make it through the open data publishing process #1204~~ _actually not present for Aug 14 but avail for July date_, SBMTD apparently uploaded a new feed before Aug 14 with no service defined until Aug 19, which results in no data from the upload date to the service definition date per https://github.com/cal-itp/data-infra/issues/1300 

I will go back far enough to get the most recent data available for each omitted operator and append it to the export.

**Comment by evansiroky** [comment]
#3383 has been resolved. @edasmalchi can you confirm if everything is looking good now?

**Comment by edasmalchi** [comment]
Briefly tried to rerun [gtfs_funnel](https://github.com/cal-itp/data-analyses/tree/main/gtfs_funnel) for august and it didn't seem to pick it up, but I'd need to investigate more to figure out why...

#1217 did get Uriel what he needed in the short term, but I'll leave this open for now until I can circle back

**Comment by tiffanychu90** [comment]
Adding a new date in `rt_dates` and then changing the reference in [update_vars](https://github.com/cal-itp/data-analyses/blob/main/gtfs_funnel/update_vars.py#L14) would get you to run [make download_gtfs_data](https://github.com/cal-itp/data-analyses/blob/main/gtfs_funnel/Makefile#L1)

**Comment by edasmalchi** [comment]
yeah, I was thinking the warehouse might have backfilled the August date though? perhaps not, I haven't tried adding a new date yet

**Comment by edasmalchi** [comment]
see #1225
