### ISSUE TITLE
Bug: Banning Transit missing from GTFS Digest

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-analyses#1254]
**Where did the bug occur?**
Select from the below, and be sure to affix the appropriate label to this issue (e.g. `dataset`, `jupyterhub`, `metabase`, `analysis.calitp.org`)
- [ ] Data (the warehouse)
- [ ] JupyterHub
- [ ] Metabase
- [ ] analysis.calitp.org  
- [x] Other: GTFS Digest

**Describe the bug**

Banning Transit should show up in the GTFS Digest, but it is not.

**To Reproduce**
1. Go to [D8 of GTFS Digest](https://gtfs-digest--cal-itp-data-analyses.netlify.app/district_08-san-bernardino)
2. Try to find Banning Transit

![Image](https://github.com/user-attachments/assets/cf7e87a1-8583-4a34-9d70-33883cdce90c)

**Expected behavior**

Banning Transit Shows up

**Additional context**

None

**Comment by evansiroky** [comment]
Banning Transit is also missing from the district digests.

**Comment by evansiroky** [comment]
I'm still not seeing Banning on the GTFS Digest website:

Missing from District GTFS Digest:

![Image](https://github.com/user-attachments/assets/fdda898a-297f-4a90-ba78-07619da4e234)

Missing from Individual Agency GTFS Digest:

![Image](https://github.com/user-attachments/assets/533c6050-4dd0-48df-aedf-7ee1e7c1d3ab)

**Comment by evansiroky** [comment]
It's showing up now. Thanks, @amandaha8!

**Comment by evansiroky** [comment]
Reopening this as I think a regression has happened. City of Banning is not an NTD reporter, so it may not be showing up due to something trying to join with NTD data. cc @amandaha8.

**Comment by amandaha8** [comment]
@evansiroky City of Banning is now back. You were right, I had dropped any operators that didn't have a value in the `ntd_id` column so City of Banning (along with other non NTD reporters) were accidentally dropped.
