### ISSUE TITLE
Research: downloading PEMS data

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#154]
## Question

Get PEMS data, see which dataset should be downloaded, maybe pushed into BigQuery? PEMS data may help us answer how fast are cars traveling along the streets bus routes are also traveling along. This helps us better understand traffic speeds by various times of day to help calculate car travel times when traveling along parallel-to-SHN bus route.

## Metrics

* Is data available only along detectors on the freeway / SHN?
* Is data available for local streets and roads?
* How often should we download? What tools to download gzipped files, unzip, basic data cleaning, then push to BQ?

## Data sources

* PEMS

## (Data Services Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by hunterowens** [comment]
not a blocker, but I will hopefully get PEMS included in the Enterprise data warehouse from IT, but that won't be online till December-January 2022-23

**Comment by tiffanychu90** [comment]
PEMS is part of the Modern Data Stack Accelerator and has been scoped for work with CalData.
