### ISSUE TITLE
MSD Dashboard Metric: Number of feeds with data about physical accessibility

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-analyses#165]
## Question

How many feeds have data about physical accessibility?

This question can be answered by resolving cal-itp/data-infra#561 and cal-itp/data-infra#562, therefore it is blocked for now.

## Metrics

The exact criteria deciding whether a feed "has data about physical accessibility" could be determined in various ways. See proposed idea for an MVP or a more rigorous analysis.

MVP:

- Presence of `stops#wheelchair_boarding` field
- Presence of `trips#wheelchair_accessible ` field
- Presence of non-empty pathways table when at least one child_stop within parent_stop exists in stops

More rigorous analysis:

- Require minimum percent of:
  - Rows in stops table with `wheelchair_boarding` field set to "not unknown" value
  - Rows in trips table with `wheelchair_accessible` field set to "not unknown" value
  - Child_stops within a parent_stop that can reach every other child_stop within parent_stop when simulating travel as an able-bodied person

## Data sources

- Static GTFS
  - `stops#wheelchair_boarding`
  - `trips#wheelchair_accessible`
  -  Pathways data as it relates to child and parent stops

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by e-lo** [comment]
> MVP:
> 
> Presence of stops#wheelchair_boarding field
> Presence of trips#wheelchair_accessible field
> Presence of non-empty pathways table when at least one child_stop within parent_stop exists in stops

Can we make the MVP at least some non-blank values?  Should be trivially more diff.

**Comment by tiffanychu90** [comment]
Notebook work completed. Validations and checks now tracked differently in GTFS Features dashboard.
