### ISSUE TITLE
MSD Dashboard Metric: Number of feeds with Fares v2 data

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-analyses#166]
## Question

How many feeds that we track have Fares v2 data?

## Metrics

The total number of feeds that have a non-empty `fare_leg_rules.txt` file.

## Data sources

A number of new files are being proposed to be added to the static GTFS specification together called "Fares v2". See [reference doc](https://bit.ly/gtfs-fares). The MVP for checking this however is to simply assert that the `fare_leg_rules.txt` file is present and it contains at least one potentially empty row. 

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by e-lo** [comment]
> The MVP for checking this however is to simply assert that the fare_leg_rules.txt file is present and it contains at least one potentially empty row.

Can't we just check that it has a non-empty row?

**Comment by tiffanychu90** [comment]
Notebook work related to this is completed. This metric is tracked differently under v2 with new tables.
