### ISSUE TITLE
Metric: number of feeds with no critical validation

### ISSUE THREAD

**Issue by machow** [cal-itp/data-analyses#167]
## Question

* Number of feeds with no critical validation errors (schedule or realtime)?

## Metrics

* TODO

## Data sources

* transit database (TODO: link)
* a spreadsheet or something else, describing what errors are critical (TODO: michael to link)
  - Note: there's a [list on this website](https://dot.ca.gov/cal-itp/critical-gtfs-validation-errors)

**Comment by tiffanychu90** [comment]
Notebook work completed. Validations and checks now tracked differently in GTFS Features dashboard.
