### ISSUE TITLE
MSD Dashboard Metric: Number of feeds with GTFS-Realtime

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-analyses#168]
## Question

How many assessed operators have a complete set of associated GTFS-Realtime feeds?

## Metrics

* An assessed operator is considered to have a complete set of associated GTFS-Realtime feeds if the existence of all three types of GTFS-Realtime feeds (Trip Updates, Vehicle Positions, Service Alerts) can be confirmed.

## Data sources

* Airtable via data warehouse

## Depends on

- [ ] cal-itp/data-infra#979

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by tiffanychu90** [comment]
Tracking this in Metabase GTFS Features Dashboard
