### ISSUE TITLE
Research: How many validators for Thruway Buses`

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-analyses#179]
## Question

Similar to to the LOSSAN question @edasmalchi answer, Gillian would like to know "how many validators would be needed" to outfit the ` can he find the thruway buses that connect to CCJPA, LOSSAN and SJRRA?`

## Metrics
How many validators would be needed for the Thruway bus services

## Data sources

* NTD 
* GTFS schedule 

Some nuance here is needed, since Amtrak isn't the operator / owner of many of its buses. Gillian is looking up ways to get a diff estimate of # of buses in the fleet, but we can guesstimate for now

## (Data Servicess Team to Copy and Fill Out Below)

The QuVR MD template below will be filled out by a member of the data services team.
This allows us to describe the request, in a way that is easy to hand-off for analysis.
After the research phase, we will sync with the asker to figure out if the metric and dashboard pieces are needed.

Before starting research:

* **Question**: Question written as a single sentence.
* **View**: E.g. `views.gtfs_schedule_fact_daily_feed_files`.
* **Research**:
  - How should the results be presented?
  - When are they needed by?

After reviewing research with the asker:

* **Metric**: what specific calculations are needed?
* **Dashboard**: where should we put the result?

**Comment by edasmalchi** [comment]
Gonna go ahead and close this one out -- I think I remember this being a case of not being able to find the answer via GTFS. I believe we may have got it via other channels.
