### ISSUE TITLE
Research: Consolidated Agreements- Overlap between DLA and DRMT

### ISSUE THREAD

**Issue by natam1** [cal-itp/data-analyses#188]
## Questions

- How many organizations in BlackCat have Master Agreements (MA) with DLA? How many TIRCP recipients also have MA with DLA? 
- How many of those organizations use the Program Supplement process?

## Metrics

To start:
* Percent Overlap
* Percent using supplemental MA process
* Percent of MAs that come back from legal unchanged

## Data sources

* BlackCat Grant Data
* TIRCP Grant Data
* DLA Agencies and Locodes

**Comment by hunterowens** [comment]
did we update Maya and Gillian with the results of this?

**Comment by amandaha8** [comment]
We didn't get any Master Agreement info, but emailed Maya and Gillian a huge Excel list of overlapping applicants across DLA, TIRCP, and Black Cat back in late April.
