### ISSUE TITLE
Research: Transit Stacks Analysis 

### ISSUE THREAD

**Issue by amandaha8** [cal-itp/data-analyses#190]
## Data Questions:

- How competitive is the market for transit technology? Alternatively, how fragmented is the market?
- What % of vendors with scheduling software also provide GTFS data out of the box? 
- What are the most common components organizations are buying?
- Are organizations buying products with overlapping functions? If so, which functions? 
- How many components are available in products versus how many components are organizations using?
- Why are organizations buying/using some components but not others? 
- Which parent companies & vendors are most present/popular/used? 
- Are there any products with GTFS and Realtime capabilities that nobody is using?
- Get basic information on agencies who use popular Realtime products: are they small/big, urban/rural, etc?

## Metrics:

- Above. 

## Data Sources:

* [Transit Stacks on Airtable](https://airtable.com/appeVUdmRBi3K9hTS/tblsoJGdAKsErUPY6/viwGmaYRrLio8xO3r?blocks=hide). 
* Initially used the products, contracts, and components tabs. 
* However, after presenting the initial findings and discussing with E, using service-components data set instead to do analysis. 
* [Also using NTD Airtable data to answer questions about agencies.](https://airtable.com/appPnJWrQ7ui4UmIl/tblLx630e56F0IJOj/viwKWzBsPUQRXAO4i?blocks=hide)

## Deliverables
* [Google Slide Deck](https://docs.google.com/presentation/d/1zOOzmIuKzGoioBAbwL0Ojeq-zCOsaCyxwUbn-WPkkt8/edit#slide=id.g129acf6324e_0_210)
* [Info about agencies that use certain RT products](https://console.cloud.google.com/storage/browser/_details/calitp-analytics-data/data-analyses/transit_stacks/agency_vendor_question.xlsx;tab=live_object?project=cal-itp-data-infra)

**Comment by holly-g** [comment]
Done! See [Google Slide Deck](https://docs.google.com/presentation/d/1zOOzmIuKzGoioBAbwL0Ojeq-zCOsaCyxwUbn-WPkkt8/edit#slide=id.g129acf6324e_0_210)
