### ISSUE TITLE
Configure Google Analytics on new site

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-analyses#192]
With the launch of https://analysis.calitp.org, we should configure the site with a Google Analytics property under Cal-ITP's organization.

I created a new property and corresponding Web stream, here's the basic configuration:

*(add in the `<head>` of each page)*

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JCX3Z8JZJC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JCX3Z8JZJC');
</script>
```

/cc @themightychris if you have thoughts around doing this with GTM instead?

**Comment by thekaveman** [comment]
Hey @charlie-costanzo - was this change deployed? I'm still seeing the older GA tag:

![image](https://user-images.githubusercontent.com/1783439/166284947-1825dc4f-0fac-4b74-ba01-4685d006d2f5.png)

**Comment by charlie-costanzo** [comment]
hey @thekaveman - thanks for catching this. `sphinx` should automatically be injecting the GA tag into generated pages but these were generated before we implemented the change so they might need to be generated again. I'll look into it!
