### ISSUE TITLE
Feature Request: CSS templates 

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#252]
**Where does your feature apply?**
Select from the below, and be sure to affix the appropriate label to this issue (e.g. `dataset`, `jupyterhub`, `metabase`, `analysis.calitp.org`)
- [ ] Data (the warehouse)
- [ ] JupyterHub
- [ ] Metabase
- [ ] analysis.calitp.org  
- [x] Other (add detail)

**Is your feature request related to a problem? Please describe.**
Currently, rendered GH pages uses `jekyll-minimal`, which looks pretty bare compared to `analysis.calitp.org`.  

**Describe the solution you'd like**
Add a CSS template for GH pages look more like analytics.calitp.org or reports.caliltp.org.

**Describe alternatives you've considered**
analysis.calitp.org uses a `sphinx-rtd` theme. I'm not tied to that theme in particular. It seems like CSS styling would be the easiest to sit on top of existing GH pages, such as [this](https://docs.calitp.org/data-analyses/bus_service_increase/img/highways-no-parallel-routes.html) and [this](https://docs.calitp.org/data-analyses/consolidated_app/lessons_learned.html). 

Right now, styling is done within a notebook. Beyond using the Cal-ITP color palette for charts, there's no much standardization elsewhere.

Any alternative that applies a template over HTML and Markdown pages within the `data-analyses` repo will work!

**Additional context**
Epic #250. This is a feature request / ticket for Ryon's work.

**Comment by amandaha8** [comment]
When printing out a data frame, it would be great to have style it with a scrollbar, remove the gray-white banding (at least IMO) and center  the text.

**Comment by tiffanychu90** [comment]
Not sure if we want some similarities to how our analysis.calitp.org looks, especially for styling of tables / fonts. Here's an [example](https://analysis.calitp.org/parallel_corridors/district_07-los-angeles/23__competitive-parallel-routes__district_07-los-angeles__itp_id_182.html) of the basic `sphinx-rtd` theme Jupyterbook uses.

**Comment by ryon** [comment]
Hi @tiffanychu90, all of the links to GH pages in this issue seem to be 404ing for me. Do I need access, or are there any new links to look at? I could use some good targets for styling. Thanks!

**Comment by tiffanychu90** [comment]
@ryon: Thanks for catching that...I didn't realize someone turned off GH pages. All the links should be working now! Some are very plain, some have attempted at adding very simple stuff like colored line breaks.

**Comment by tiffanychu90** [comment]
@ryon: See my comment in #312. This feature request only really applies to having better styling for the HTML pages in the repo, which were created from notebooks. If Markdown files also get better styling, that's nice, but not the primary use case, since even without the additional styling, it suited the existing needs. But, HTML pages have a big need for better styling, since those are shown to the stakeholders.

**Comment by tiffanychu90** [comment]
No progress, Jarvus contract winding down
