### ISSUE TITLE
Research Task - RT Trips Ran vs Scheduled 

### ISSUE THREAD

**Issue by natam1** [cal-itp/data-analyses#263]
## Research Task

Compare GTFS RT trips scheduled vs trips ran 

* **Question or Goal**: overarching goal of this issue  
* Understand how operators run service 

* **Data Required**:
  * Currently have:
       *   GTFS RT Warehouse 

* **Research Required**:  

* **Metrics**: what specific calculations are you loooking to find?  
* Percent Ran 
      * By route 
      * By Operator

* **Expected Outputs / Findings**: what do you hope to have created when this is complete?
* tbd

**Comment by natam1** [comment]
Adding in a [sample of data for May 4th, 2022](https://github.com/cal-itp/data-infra/tree/rt_sched_may_4_sample) available in [`cal-itp-data-infra-staging.natalie_views`](https://console.cloud.google.com/bigquery?authuser=3&project=cal-itp-data-infra-staging&supportedpurview=project&ws=!1m5!1m4!4m3!1scal-itp-data-infra-staging!2snatalie_views!3sgtfs_rt_vs_schedule_trips_may4_sample)

**Comment by tiffanychu90** [comment]
* Scope of this under v1 is done. Current work for v2 tracked here: https://github.com/cal-itp/data-infra/issues/2236
