### ISSUE TITLE
(Support Roadmap) Processes to identify good-quality data

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-analyses#285]
## User stories

By nature of our business goals, portions of the GTFS static schedule data that is published and consumed is going to be of poor quality. Analysts need to be able to quickly identify good-quality data that they can use for their needs.

This needs scoping, as there are a few forms this can take.

1. **Short term**: a way to capture metadata around poor data quality. What existing efforts exist? Validator tools, dbt tests…

2. **2-6 Months**: Apply analytics engineering to filter data we find inaccurate from tables analysts will be using, using tools like dbt 

This relates to the idea of:

1. Feed- and file-level versioning and quality indicators
2. Better understanding of relevant entities (files and feeds, not records) from analyst perspectives

Related work task(s): 
🔄 Provide technology, methods, and subject area support to data analysts

---

### Summary

A user story should typically have a summary structured this way:

1. **As an** analyst
2. **I want** easily know which data should be used, and which shouldn't
3. **So that** I can best use my time, and create the high-quality analysis

### Acceptance Criteria

1. Follow the steps outlined in the documentation created as part of this epic
2. I should be able to easily know which data should be used and which should be avoided during my analysis workflow
3. Opportunities to inform the data quality team of relevant data quality problems uncovered during this process have been identified

Also, here are a few points that need to be addressed:

1. Constraint [1]
3. Constraint [2]

### Notes

This is item 1A from the 2022 Analytics Support Roadmap

### Tester [Stakeholder]

1. Analyst team lead
2. Analysts

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
4. - [ ] Team has defined solution / steps to satisfy acceptance criteria
5. - [ ] Acceptance criteria is verifiable / testable
6. - [ ] External / 3rd Party dependencies identified

**Comment by charlie-costanzo** [comment]
gtfs schedule refactor
- difference between  transit data quality and one day of feed level data

**Comment by tiffanychu90** [comment]
v2 warehouse breaks out transit quality metrics with a lot more validations
