### ISSUE TITLE
(Support Roadmap) Define processes for intermediate data

### ISSUE THREAD

**Issue by charlie-costanzo** [cal-itp/data-analyses#286]
## User stories

(Definition) **Intermediate data** - data in an analysis that did not exist before the analysis existed and that will not be maintained after the analysis

Currently, in certain situations, analysts are working with intermediate data they themselves create or source, rather than data directly from our warehouse. 

This question is more related to scoping and defining processes: when this happens, what is the recommended way that data is stored, used, and in what format? What gets into the warehouse, what’s external?

1. Included: imposing more structure on GCS and Google Drive
  a. Drawing lines - what is canonical, what is not? BigQuery canonical, GCS more of a workspace. We need to present these appropriately
  b. Observing current working patterns will inform these lines that need to be drawn as well
2. Setting more norms for how data gets labeled for effective joining

🔄 Provide technology, methods, and subject area support to data analysts

---

### Summary

A user story should typically have a summary structured this way:

1. **As an** analyst
2. **I want** clearly understand what to do with intermediate data that I create or use
3. **So that** we can preserve, and use data that is produced in an analytics workflow - increasing efficiency and reducing the need to duplicate work

### Acceptance Criteria

1. Use the documentation created as part of this epic
1. I should easily know what to do with data that I produce, and how to find intermediate data that already exists

Also, here are a few points that need to be addressed:

1. Constraint [1]
2. Constraint [2]

### Notes

This is item 1A from the 2022 Analytics Support Roadmap

### Tester [Stakeholder]

1. Analyst team lead
2. Analysts

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria
4. - [ ] Acceptance criteria is verifiable / testable
5. - [ ] External / 3rd Party dependencies identified

**Comment by charlie-costanzo** [comment]
think of this in terms of standards and goals as opposed to processs 
- dbt
- not raw gcs
- tec

**Comment by tiffanychu90** [comment]
Existing workflow works for GCS / BQ. Folder structure within GCS has been in place and has worked. BQ for v2 warehouse allows analysts to query tables that are pre-joined according to our v1 work patterns.
