### ISSUE TITLE
Bug: : Missing Metrolink (ITP ID: 323) from ca_transit_routes

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#289]
**Where did the bug occur?**
Select from the below, and be sure to affix the appropriate label to this issue (e.g. `dataset`, `jupyterhub`, `metabase`, `analytics.calitp.org`)
- [ ] Data (the warehouse)
- [ ] JupyterHub
- [ ] Metabase
- [ ] analytics.calitp.org  
- [x] Other - `ca_transit_routes` dataset in open data portal 

**Describe the bug**
Metrolink is missing from `ca_transit_routes`, but `shapes` is present for 6/21/22 (date selected for running `traffic_ops/prep_data`

**To Reproduce**
1. Go to [transit routes](https://gisdata-caltrans.opendata.arcgis.com/datasets/dd7cb74665a14859a59b8c31d3bc5a3e_0/explore?location=36.114238%2C-97.095950%2C4.70)
2. Filter for ITP ID 323 (metrolink)
3. It's not there!!

**Expected behavior**
Metrolink appears in `shapes` table, but all of its `shape_id` values are holding `None` in the `trips` table. The merge using `calitp_itp_id` and `shape_id` is dropping all of Metrolink (expected behavior of the merge). Do we want to modify the script to handle exceptions where an operator filled in all missing values for `shape_id`, but it's all present in `shapes`?

**Additional context**
Merging in the `trips` table was originally intended as a way to handle edge cases where an operator does not supply `shapes` (optional in GTFS), but it runs trips. We can use `trips` and join on `stops` to get the stop lon/lat and stop sequence, and string it together to be the best known path for a route. From trips, we drop all the trip identifier columns to get the routes.

[Slack QA/QC](https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1655165119731889)

**Comment by lauriemerrell** [comment]
Ope, I accidentally commented on Tiffany's PR rather than here -- https://github.com/cal-itp/data-analyses/pull/290#issuecomment-1155496834

There is some discussion on Slack re: notifying the provider -- I'll tag you in

**Comment by tiffanychu90** [comment]
Closing issue for now, since Metrolink is does show `shape_id == None` in their `trips` table. Not an issue with how the `routes` file was generated for open data portal.

**Comment by tiffanychu90** [comment]
Investigation into `trips` table shows that only Metrolink has all missing `shape_id` values, no other operator does. Can't join at all because the `shapes` table in warehouse doesn't have `route_id`. Other than alert Metrolink, we can't carve out an exception use case to fill in the info.

**Comment by lauriemerrell** [comment]
@tiffanychu90 -- in Metrolink's case, I actually think it looks like the shape IDs (available in like `dim_shapes_geo`) might be mappable to route IDs manually via like a hard-coded dictionary or something.

Here are the results of this query -- it does seem mappable if we want to hard code handling:

```
SELECT DISTINCT shape_id, "" as route_id
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_shapes_geo`
WHERE calitp_itp_id = 323 

UNION ALL

SELECT DISTINCT "" as shape_id, route_id
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_routes`
WHERE calitp_itp_id = 323
```
[metrolink_route_shape_ids.csv](https://github.com/cal-itp/data-analyses/files/8927866/metrolink_route_shape_ids.csv)
