### ISSUE TITLE
Analysis of which validation codes, notices, etc are most frequent 

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-analyses#30]
Currently, we have all of the GTFS validator results stored in `validation_notices`, broken down by type, number of errors, and if they are resolved month to month. 

@mcplanner has put togehter a help list of "severity" of GTFS notices. We have metrics stored in [this spreadsheet](https://docs.google.com/spreadsheets/d/1uHqi-xbNioQBMfgVzC_-kN2B0LI-1e_a_FAWD72zhsE/edit#gid=0) 

let's setup a notebook or similar to track these over time

**Comment by thekaveman** [comment]
I transferred this issue from the now-archived [cal-itp/notebooks](https://github.com/cal-itp/notebooks) repo. Feel free to close and/or rework as makes sense for you all!
