### ISSUE TITLE
Bug: Missing Certain Transit Agencies on Speedmaps 

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-analyses#318]
**Where did the bug occur?**
Select from the below, and be sure to affix the appropriate label to this issue (e.g. `dataset`, `jupyterhub`, `metabase`, `analytics.calitp.org`)

- [ ] Other (add detail)

**Describe the bug**
Got an email from JWW forwarded from folks in the Napa valley, who are looking at the Speed Maps. They reported not being able to see the following agencies 

* Napa Valley Transportation Authority – Vine Transit
* Santa Rosa City Bus
* Sonoma County Transit
* County Connection
* WestCat

 
Can I get a quick reason why each of those agencies wasn't on the speedmap - for example - "No GTFS-RT, schedule information was insufficient in reason {x}, etc"

**Comment by edasmalchi** [comment]
Looks like an Airtable issue for County Connection -- it seems like itp_id is null in [Airtable California Transit: organizations](https://airtable.com/appPnJWrQ7ui4UmIl/tblFsd8D5oFRqep8Z/viwVBVSd0ZhYu8Ewm/recjnaKVDEgulsko3?blocks=hide) and 61 per `agencies.yml`. On Airtable it looks like 61 is entered as the ntd_id instead, which doesn't seem right.



The rt analysis code relies on Airtable organizations data for agency names and CT districts, so this missing itp_id probably caused County Connection to get dropped in a join...

**Comment by edasmalchi** [comment]
Here's what I've been able to find out:

* Napa Valley Transportation Authority – Vine Transit

    * trip_ids in GTFS Schedule feed do not match trip_ids in GTFS-RT feed.

* Santa Rosa City Bus
    
    * Bad luck on choice of date, see below from GTFS Service Hours Issue Tracker
    * No data on 6/1/22 - the feed we got on that day only had Monday service defined? Seems like there was a temporary bad upload that they fixed on the 2nd (tracked in [sheet](https://docs.google.com/spreadsheets/d/16tcL3fPdYkrNajDNneSR1b5ImhFOCJ0gWFnEaXyg16A/edit#gid=0))
    * _fixable by choosing a different date, like 6/8_
    
    
* Sonoma County Transit

    * Apparent issue with GTFS-RT feed, valid endpoint but file returned appears either empty or not valid GTFS-RT.
    * No vehicle positions in warehouse, a quick look at Transit App shows no current RT either.
    
    
* County Connection

    * Airtable issue on our end, see above 
    * _fixable by entering data manually and rerunning, pending Airtable fix_
    

* WestCat

    * Apparent issue with GTFS-RT feed, valid endpoint but file returned appears either empty or not valid GTFS-RT.
    * No vehicle positions in warehouse, a quick look at Transit App shows no current RT either.

**Comment by hunterowens** [comment]
Thanks! let's close this issue for now and make a new one for fixing Santa Rosa nad County Connection?
