### ISSUE TITLE
Research Request - 5310/5311 agencies who is eligible, who has applied

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#333]
Complete the below when receiving a research request, and continue to add to this issue as you receive additional details and produce deliverables. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

## Research Question
**Single sentence** description:  Which 5310/5311 agencies are eligible and have / have not received funding?
  
**Detailed** description:

From Jess Sullivan: The CRM team is trying to track down some information related to 5310/5311 eligibility. Goal is to be able to tag 5310/5311 agencies in hubspot, either as eligible/applied/received--tbd what makes the most sense to include, but we're interested in finding out what is feasible. Is that something you can help with? I have an eligibility report that I pulled from BlackCat but I'm unclear on whether there is a better way of accessing this information...If [this] is possible (getting a list of all agencies that are 5310/5311 eligible) that would be ideal.

****5311****
Create a dataset that looks like this: 
* each row is agency/org - year. columns are applied and received. in the cells, store the $ amounts.  if there are 5 years of data, let's get every agency 5 rows and assume if they don't appear, they didn't apply, and thus didn't receive anything.

This dataset is flexible enough: someone could use that and somehow tag Hubspot agencies/orgs. maybe they just use the last year and see how many applied / received, if the most current year hasn't yet awarded funding amounts. maybe they look in the last 3 years and see whether an agency has applied or received. let's keep it fairly flexible for someone else to make that decision of what the high-level metric should be.

## How will this research be used?
Which agencies are eligible for 5310/5311 funds, and who has applied/received?

## Stakeholders & End-Users
Jess Sullivan, for some high-level metrics to be tagged in Hubspot

## Metrics
* long dataframe at the agency-year level
* store funding $ in nominal dollar values

## Data sources
* **Cal-ITP data sources**: 
* 5310 black cat data - only have agencies that have successfully received funding
* 5311 black cat data - going back to 2011, have agencies that have applied/received funding (use this as the universe of 5311 agencies)

* **External data sources**:

* **Remaining data source questions**:

## Deliverables:
A python script or notebook wrangling dataframe into this format. Export to Excel or Google Sheet.

**Comment by j-h-sullivan** [comment]
One more request for this! Can we include transit agency domain name? I believe the url is used as the unique identifier for each agency. Thank you!

**Comment by tiffanychu90** [comment]
@amandaha8 @aly-medina:

For transit agency domain name, see if it's an easy merge to go from black cat organizations to ITP IDs. If you can get it to ITP ID, there's a table in the warehouse, probably `tbl.gtfs_schedule_agency_name` that can get you ITP ID to agency domain name.

**Comment by amandaha8** [comment]
@e-lo  Yes, it's a simple Excel sheet with organization name, website from Airtable, and how much funding they received in the past 5 years.  [It's called 5311-5310-hubspot here.](https://console.cloud.google.com/storage/browser/_details/calitp-analytics-data/data-analyses/5311-5310/5311_5310_hubspot.xlsx;tab=live_object?project=cal-itp-data-infra)
