### ISSUE TITLE
New Team Member - Alyssa Medina

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#335]
Name: Alyssa Medina
Role: Temp assignment
Reports to: Evan

Google Workspace Email Address:  alyssa.medina@dot.ca.gov
GitHub Username:  aly-medina
Slack Username: Alyssa Medina

**Set-up:**
- [x] Technical Onboarding call scheduled: Holly onboarded with JupyterHub. Amanda onboarded with using notebooks / quick intro to Python. 

- [ ] Added to tools:
  - [ ] Github
    - [ ] Organization: Cal-ITP
    - [x] Team: warehouse-users
  - [x] JupyterLab
  - [x] Google Cloud Console
  - [x] Metabase
  - [x] Slack

- [ ] Added to meetings:
  - [ ] Daily Stand-ups
  - [x] Lunch n' Learn

- [x] Added to Slack channels:
  - [x] #data-analyses
  - [x] #data-office-hours
  - [x] #lunch-n-learn

**Comment by charlie-costanzo** [comment]
ah @tiffanychu90 it looks like [these tickets were also spun up in data-infra](https://github.com/cal-itp/data-infra/issues/1659)

**Comment by tiffanychu90** [comment]
Ahh, couldn't find it here, and couldn't figure out why some permissions were granted but not all
