### ISSUE TITLE
New Team Member - Katrina Kaiser

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#336]
Name: Katrina Kaiser
Role: Research Data Specialist III
Reports to: Hunter Owens

Google Workspace Email Address:  katrina@calitp.org
GitHub Username:  
Slack Username: Katrina M. Kaiser

**Set-up:**
- [ ] Technical Onboarding call scheduled

- [ ] Added to tools:
  - [ ] Github
    - [ ] Organization: Cal-ITP
    - [ ] Team: warehouse-users
  - [ ] JupyterLab
  - [ ] Google Cloud Console
  - [ ] Metabase
  - [ ] Slack

- [ ] Added to meetings:
  - [ ] Daily Stand-ups
  - [ ] Lunch n' Learn

- [ ] Added to Slack channels:
  - [ ] #data-analyses
  - [ ] #data-office-hours
  - [ ] #lunch-n-learn

**Comment by charlie-costanzo** [comment]
ah @tiffanychu90 it looks like [these tickets were also spun up in data-infra](https://github.com/cal-itp/data-infra/issues/1644)

**Comment by tiffanychu90** [comment]
Close in favor of `data-infra` one
