### ISSUE TITLE
Research Request - 5311 and 5310 Payment  

### ISSUE THREAD

**Issue by amandaha8** [cal-itp/data-analyses#368]
## Research Question
**Single sentence** description:  
 Understanding the payment practices of recipients of 5311 and 5310 funds.

## How will this research be used?
What will be achieved or informed? What is the intended impact?

## Stakeholders & End-Users
Cal ITP Program Manager. 

## Metrics
* How many 5311 and 5310 agencies accept only cash (and who are they)?
* How many 5311 agencies have an “app” as well, and who are they, and which app (and can we get a copy of the contract)?
* How many of the 5311 agencies (and which ones) accept payment by credit/debit for passes (and who is their processor)? 
* Which are the 5311 agencies?
* Of the 5311 agencies, which ones do not have GTFSRT?
* Of the 5311 agencies that do not have GTFSRT, which ones have CAD/AVL?
* Of the 5311 agencies that do not have GTFSRT and do not have CAD/AVL, do they need CAD/AVL?
* Of the 5311 agencies that do not have GTFSRT, do not have CAD/AVL and do not need CAD/AVL, how are they to produce GTFSRT?
* What are the pros and cons of relying on CAD/AVL for vehicle location and GTFSRT, regardless of whether an agency is 5311 or not (putting aside the large agencies)?
* Are CAD/AVL systems based on mobile and in the cloud? If not, what are the hardware dependencies?
* Are CAD/AVL systems based on mobile and in the cloud? If not, is the software dependent on the legacy hardware?
* How many fixed route agencies (and who are they) that have fewer than 25 vehicles?

## Data sources
* **Cal-ITP data sources**: 
* All from Airtable
* Transit Stacks - Service Components
* Organizations
* Fare Systems
* Services

* **Remaining data source questions**:
* Black Cat Data
* NTD Vehicles

## Deliverables:
* [Google doc.](https://docs.google.com/document/d/1C5V99HYUdBOyb8OYARMZFO-uHyNiYfPUOHvegU44ulg/edit?usp=sharing) 
* [Merged data](https://docs.google.com/spreadsheets/d/1QemBYUI20_9GonyXsEu7hlTZdDc99lqPY6VSt51UgUo/edit#gid=2138962969)

## Timeline of deliverables:
End of September

**Comment by hunterowens** [comment]
gonna work with @safrazier17 once @amandaha8 completes initial analysis

**Comment by hunterowens** [comment]
few more questions from Gillian to add to this, not in scope for intial version @amandaha8 


Which are the 5311 agencies?
Of the 5311 agencies, which ones do not have GTFSRT?
Of the 5311 agencies that do not have GTFSRT, which ones have CAD/AVL?
Of the 5311 agencies that do not have GTFSRT and do not have CAD/AVL, do they need CAD/AVL?
Of the 5311 agencies that do not have GTFSRT, do not have CAD/AVL and do not need CAD/AVL, how are they to produce GTFSRT?
What are the pros and cons of relying on CAD/AVL for vehicle location and GTFSRT, regardless of whether an agency is 5311 or not (putting aside the large agencies)?
Are CAD/AVL systems based on mobile and in the cloud? If not, what are the hardware dependencies?
Are CAD/AVL systems based on mobile and in the cloud? If not, is the software dependent on the legacy hardware?

**Comment by amandaha8** [comment]
I added the new questions in!
