### ISSUE TITLE
Research: How many operators is Cal-ITP assessing?

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-analyses#379]
## User Story

**As a** Cal-ITP program manager or more senior Caltrans executive, 
**I want to** know how many transit agencies are being assessed in California 
**so that** I can have a baseline for calculating other metrics like the one described in cal-itp/data-infra#984.

### Additional Context

The gist of this question lays the foundation for answering a variety of questions that high-level executives asks such as "what percent of transit agencies have GTFS Schedule data?" or "what percent of transit agencies have Fares v2?" or "what percent of transit agencies are GTFS-compliant?"

Research should be performed with various stakeholders to determine how to define and filter the data we have in airtable about organizations, services and potentially other items. Part of this task should include a document detailing how to filter the data in airtable in order to provide this baseline for measurement. If none of the stakeholders can give a clear answer about how to calculate this baseline, a deliverable of this report should propse at least one recommended option for calculating this baseline.

## Acceptance Criteria

**Given** the data Cal-ITP has collected about transit agencies with respect to how they are funded, what kind of service they operate, and any other relevant critieria
**When** applying all relevant criteria about what qualifies as a transit agency for reporting purposes
**Then** a number should be calculated.

The deliverable of this should include:

1. A memo containing the precise, quantifiable and measurable definition of what qualifies as a transit agency for answering the above-mentioned high-level questions
2. A metabase question that simply shows the resulting number of transit agencies when applying the criteria to the data in airtable

## Sprint Ready Checklist

- [ ]  Acceptance criteria defined
- [ ]  Team understands acceptance criteria
- [ ]  Team has defined solution / steps to satisfy acceptance criteria
- [ ]  Acceptance criteria is verifiable / testable
- [ ] Dependencies identified

## Appendix

The document [Cal-ITP Transit Provider Categorization + Activities](https://docs.google.com/document/d/1e0Z-aLKzNg7xnP0gSCCSWOuNPjTB8xN1G7vWVYQ8bYk/edit#heading=h.5taosqpsjhbq) is a detailed document about the various ways that transit agencies could be categorized, but it does not include a recommendation for how to establish a baseline for reporting.

There already exists a filter within airtable that seems to do something with regarding filter assessed operators. Research should be done to determine if this is relevant. Screenshots of this filter is shown below:

### Overall airtable filter

<img width="685" alt="Screen Shot 2022-01-24 at 2 16 29 PM" src="https://user-images.githubusercontent.com/3112493/150875059-68e87b3e-0f0a-45ab-8eb6-d7573e75f644.png">

### Reporting Category

<img width="536" alt="Screen Shot 2022-01-26 at 10 32 56 AM" src="https://user-images.githubusercontent.com/3112493/151243846-7ec3060a-1e61-4490-ab53-4edb172136f9.png">

### Currently Operating

<img width="539" alt="Screen Shot 2022-01-26 at 10 32 52 AM" src="https://user-images.githubusercontent.com/3112493/151243850-13daae98-5022-45cd-a4d8-861d6f3eeeda.png">

### Service Type

<img width="520" alt="Screen Shot 2022-01-26 at 10 32 47 AM" src="https://user-images.githubusercontent.com/3112493/151243852-376562dd-eda6-4b0d-a922-ddf01b5d9601.png">

### Additional service type filter

<img width="243" alt="Screen Shot 2022-01-26 at 10 32 28 AM" src="https://user-images.githubusercontent.com/3112493/151243854-16563456-169e-473d-b738-f25a8aa1b2ac.png">

**Comment by tiffanychu90** [comment]
Tracking this in Metabase GTFS Features Dashboard
