### ISSUE TITLE
Research Task - How many GTFS shapes have overlapping start/end?

### ISSUE THREAD

**Issue by KatrinaMKaiser** [cal-itp/data-analyses#387]
## Research Task

* **Relevant PR** (if applicable):  #409 
* Initial work [notebook](https://github.com/cal-itp/data-analyses/blob/kmk-rt-work/rt_delay/id_shape_overlap.ipynb)

* **Question or Goal**: How many GTFS shapes start and end on top of each other? This known issue with the speedmaps means vehicle positions are "snapped" to shapes in wrong order. Calculated speeds are implausible and trips are filtered out from maps.

* **Data Required**:
  * Currently have: GTFS Shapes
  * Need:  

* **Research Required**:  Which specific table is appropriate to pull from (something in views or using the get_stops function from gtfs_utils that pulls from the dim table?  

* **Metrics**: 
* For each operator, how many routes (shapes) have this overlap issue? 
* For each operator, how many trips (from schedule) on a representative weekday would be subject to this drop condition?

* **Expected Outputs / Findings**: Quantify how many routes have overlap, and how many trips would currently be dropped. Consider a cleaning solution wherein starts/ends of these shapes are buffered and trimmed so that we can drop the initial/ending vehicle position points but show speed data for the majority of the route.

**Comment by edasmalchi** [comment]
just merged a PR attempting an initial fix, did not fully solve for KART

ideas for a future issue:

- more closely investigate interplay with progressing positions cleaning step
- find problematic midway loops
- consider dropping stops in zones of confusion as well
- consider approaches at the stop_delay_view/segment_speed_map level

let's keep this issue around for the prevalence analysis and create another for an improved fix when our capacity allows

**Comment by edasmalchi** [comment]
closing to track in #594
