### ISSUE TITLE
Research Task - Make sure HQTA points/polygons data is correct

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#398]
## Research Task

Use this template to create issues that represent small chunks of work (.5 - 2 days) that stand alone, or represent incremental work as part of an [Epic Issue Template](https://github.com/cal-itp/data-analyses/issues/new?assignees=&labels=epic&template=epic.md&title=Epic+-+%5BResearch+Request+Project+Title%5D).

* **Relevant PR** (if applicable):  

* **Question or Goal**: **BUG**: @edasmalchi noticed in the published open data portal, the CA HQ points datasets has incorrect points. [Slack thread](https://cal-itp.slack.com/archives/C03JL54P8QY/p1661822418098349) 

* Double check July data to make sure it's ok, and push that through metadata rewrite and overwrite what's published.

* **Data Required**:
  * Currently have:
  * Need:  

* **Research Required**:  

* **Metrics**: what specific calculations are you looking to find?  

* **Expected Outputs / Findings**: what do you hope to have created when this is complete?

**Comment by edasmalchi** [comment]
@tiffanychu90 Actually the points dataset [CA HQ Transit Stops](https://data.ca.gov/dataset/ca-hq-transit-stops1) seems ok, rather it's the polygon dataset [CA HQ Transit Areas](https://data.ca.gov/dataset/ca-hq-transit-areas1) that has all the major stops on what looks like a single point/small buffer. Apologies for being unclear on Slack.
