### ISSUE TITLE
Research Task - function to easily view/generate rt_delay data

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#472]
## Research Task

* **Question or Goal**: Analysts should be able to easily find out if rt_delay intermediate data is already present on a given date, and if not have the option to generate it using rt_analysis.OperatorDayAnalysis and rt_analysis.OperatorDayAnalysis.export_views_gcs() without using or modifying rt_delay/04_generate_all.ipynb

* **Expected Outputs / Findings**: A function (in shared_utils.rt_utils?) that enables this sort of process

* **Notes**: See initial work at end of https://github.com/cal-itp/data-analyses/blob/main/rt_delay/23_sccp.ipynb

**Comment by KatrinaMKaiser** [comment]
new util `get_operators` in `shared_utils.rt_utils`
