### ISSUE TITLE
Epic - 100 Routes to Better Buses

### ISSUE THREAD

**Issue by KatrinaMKaiser** [cal-itp/data-analyses#494]
### Summary: This epic is for tracking PRs/smaller issues on this deliverable
* Leverage existing GTFS-RT work (speedmaps, comparisons with SHN) to deliver ~10 recommendations to each district
    * Transit Corridors
    * Intersection/Spot treatments
    * SHN segments with transit service opportunities

### Notes, misc:
*  [Exec Board Presentation](https://docs.google.com/presentation/d/1EnmYkq7ebESxLqctWEdc0nt81pheH660zIktB0SRF4c/edit#slide=id.)

### Reviewers [Stakeholders]

1. @tiffanychu90 
2. @edasmalchi 
3. @KatrinaMKaiser 

## Issues

- [ ] 1. #441 (portfolio deployment)
- [ ] 2. #

### Deliverables
* Parameterized notebook [site](https://analysis.calitp.org/one-hundred-recs/README.html)
* Spreadsheet of recommendations, for tracking action
* shapefiles/geoJSON for districts to use in planning

**Comment by edasmalchi** [comment]
may reboot as part of the SB125 work!

**Comment by edasmalchi** [comment]
on-system we've learned a lot through the transit priority work
off-system, cover via other SB125 issues

**Comment by edasmalchi** [comment]
giving ourselves more credit
