### ISSUE TITLE
Epic - Dashboard to track overall progress on GTFS features + statuses

### ISSUE THREAD

**Issue by juliama0780** [cal-itp/data-analyses#503]
An epic addressing [data issue #1781](https://github.com/cal-itp/data-infra/issues/1781) to create a GTFS features dashboard for interested parties

### Summary
* From Issue Text: 

> As Gillian, I would like to be able to refer the public and decision-makers to a dashboard where at a glance, they can see the status of and progress that is being made in real-time on GTFS features (and their effect on customer experience).

> As a decision-maker evaluating the usefulness of Cal-ITP, I would like to be able to see if and how progress is being made in order to understand the potential future ROI of the Cal-ITP program.

> As an agency decision-maker, I would like to understand where I, my peers, and various vendors fall within the spectrum of transit data performance.

### Research required:
* What GTFS features services provide
* Research into previous tasks for 5307, 5310, and 5311 recipients, FTA Mode Types and ridership metrics (VOMS, service hours)
* Rest  to be determined in future issues 

### Notes, misc:
* Need deliverable by budget season March 2023 

### Reviewers [Stakeholders]

1.

## Issues

- [ ] 1. #504 
- [ ] 2. #599 

### Deliverables
* Metabase Dashboard

**Comment by natam1** [comment]
Closing Epic for now. Potential to update/expand scope in the future.
