### ISSUE TITLE
Update dashboard for version 2

### ISSUE THREAD

**Issue by juliama0780** [cal-itp/data-analyses#660]
## Research Task

Received feedback for the dashboard and will be updating the draft version of the dashboard in [this link](https://dashboards.calitp.org/dashboard/123-gtfs-features-dashboard-draft-2).

- We will be using _dim_contracts_ instead of _dim_service_components_.

- Modify keys of datasets (Source ID vs Key)

- Add in SQL code to obtain fixed-routes

- Perform quality control checks on calculations and filters

* **Goal**: Modify dashboard

**Comment by juliama0780** [comment]
#503

**Comment by natam1** [comment]
Closing out for v1 of dashboard
