### ISSUE TITLE
Research Request - crosswalk for keys (feed_key, gtfs_dataset_key, source_record_id, name, organization_name) when aggregating

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#750]
Complete the below when receiving a research request, and continue to add to this issue as you receive additional details and produce deliverables. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

## Research Question
**Single sentence** description:  Moving from single day to some aggregation requires us to use different keys. Lay out best practices and crosswalks for how to traverse various levels of aggregation.
  
**Detailed** description: Perhaps we should always be publishing (open data portal, portfolio) showing some combination of `source_record_id` and `organization_name` and `base64_url`, even if we're publishing single day. 

Probably coalesce several functions lying around:
* `rt_utils`: Eric has a [get_speedmaps_ix_df](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/rt_utils.py#L307-L350) 
* `gtfs_utils_v2`: [organizations to gtfs_dataset_keys](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_utils_v2.py#L220-L240)
* `gtfs_utils_v2`: uses above and goes additional level of grabbing [schedule feed_key for a single day](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_utils_v2.py#L243-L303)

## How will this research be used?
Analysts.

## Deliverables:
Add this as a function in `shared_utils`. Lay out best practices in our docs.

**Comment by lauriemerrell** [comment]
Sorry to butt in but I just saw this go by on Slack and wanted to flag the documentation that already exists on the [dbt docs site](https://dbt-docs.calitp.org/#!/overview)

![image](https://github.com/cal-itp/data-analyses/assets/55149902/1bcbd614-d851-4c9f-9b58-fbec342bc84d)

(And in pasting this image I noticed the bottom right cell in the table is wrong, I will correct it)

**Comment by tiffanychu90** [comment]
@lauriemerrell Oh, not adding to dbt, I think we've been inconsistent, since we typically use `feed_key` and `gtfs_dataset_key` in doing the analysis. But the names we've been showing differ, sometimes it's just a cleaned up `gtfs_dataset_name` or sometimes `organization_name`. I'd like to move to a more standardized, consistent naming when we present our work, since we're not really doing it now.

I think moving forward, whether we're aggregating or not, we should probably lay out how to get from our unit of analysis to a published name that we're displaying to the public (open data portal and analysis.calitp.org, any presentations we make). For single day, even if we're doing our work with `feed_key`, the last step should always be to get out the `source_record_id`. For an aggregated date, we're not using `feed_key`, we're using `source_record_id`.
