### ISSUE TITLE
Research Request - traffic signals + slow speeds

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#783]
Complete the below when receiving a research request, and continue to add to this issue as you receive additional details and produce deliverables. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

## Research Question
**Single sentence** description: Use a rough heuristic to find roughly where there are slow speeds near traffic signals as proxies for signals that could benefit from traffic signal priority (TSP).
  
**Detailed** description: 
Since we have not aggregated, even at a single stop, right now, only across trips by segment, we can't implement delay at a single intersection across operators. A particular intersection means we have to associate a certain direction and aggregate across all trips and operators at that point. 

More simply, signals that can benefit from TSP are roughly associated with slow speeds approaching. Probably, the segment the signal falls is is probably enough to tell us a rough ranking. Signals with more trips and slower speeds should be prioritized within each district.

Even this approach of finding all the segments that intersect with a traffic signal is going to face some aggregation issue. Rather than finicky calculations, stick with some method that's consistent with rankings as an output.
## How will this research be used?
Traffic Ops doesn't know where to prioritize signals. In the longer-run, Traffic Ops should probably figure out how they would use speeds data themselves.

We can solve the aggregation issue on a corridor (road segments)...make that available on the open data portal...after stop segments work concludes. 

## Stakeholders & End-Users
Traffic Ops.

## Metrics
* Simple spatial join of intersection to segment and get some aggregated speed metric across operators. 
* Should we convert this speed to delay? Should this be weighted average delay across trips & operators? Sum of estimated delay? 
* If goal is ranking, speed or delay would give us the same results anyway....

## Data sources
* **Cal-ITP data sources**: Speeds by segment in some form. Use speeds that are aggregated across trips. Perhaps peak trips?

* **External data sources**: Traffic Ops provided excel sheet for traffic signals.

* **Remaining data source questions**:

## Deliverables:
Notebook, dashboard, narrative, presentation details.

## Timeline of deliverables:
Estimated completion date

**Comment by hunterowens** [comment]
fwiw, this seems like the right approach. I think as long as we say "here are the reasonably targeted list of intersections", we can defend any metric

**Comment by tiffanychu90** [comment]
* #835
