### ISSUE TITLE
Research Request - use vehicle positions near stop as actual_stop_arrival

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#785]
Complete the below when receiving a research request, and continue to add to this issue as you receive additional details and produce deliverables. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

## Research Question
**Single sentence** description:  Find GTFS RT vehicle positions nearest stop to get actual stop arrival.
cc #719 
  
**Detailed** description: 
As the next phase of schedule vs RT work: Implement interpolation of vehicle positions nearest stops. Pick one of the two approaches:
* last position prior to a given stop
* last position prior to a given stop and first position after the stop, average the timestamps (done currently in speedmaps).

## How will this research be used?
Use RT to back out a modified `stop_times` table with actual stop arrivals (vs schedule stop arrivals in GTFS schedule). Can be used in Conveyal.

## Metrics
* actual stop arrival for each trip-stop

## Notes
* include a stage to pare down vp
* functions used to take at least 2 trips across 2 operators

## Data sources
* **Cal-ITP data sources**:
* vehicle positions on a single day
* schedule `stop_times`...use this as template for operator-trip-stop columns. generate the RT corresponding `arrival_time` column as `actual_arrival_time` 
* GitHub folder: `rt_schedule_v_ran` and GCS folder: `rt_vs_schedule`

**Comment by edasmalchi** [comment]
goal: interpolate using before/after points as in `rt_analysis`, but first filter the universe of vehicle positions to a more manageable level
