### ISSUE TITLE
Research Task - SB125 Requirements and Performance Metrics

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-analyses#817]
## Research Task
[SB 125](https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB125) is passed, which start a transit transformation task force, which will require data, plus KPIs and transit metrics.

* **Relevant PR** (if applicable):  

* **Question or Goal**: overarching goal of this issue  
Determine datasets that we have, metrics we want, draft 

* **Data Required**:
  * Currently have:
  * Need:  
TKTK
* **Research Required**:  
TKTK 
* **Metrics**: what specific calculations are you looking to find?  

* **Expected Outputs / Findings**: what do you hope to have created when this is complete?

@edasmalchi @tiffanychu90

**Comment by tiffanychu90** [comment]
[Slack - Scott Frazier wrote SB 125 summary](https://cal-itp.slack.com/archives/C014Q6G3VCJ/p1690399516418199)

**Comment by edasmalchi** [comment]
to close pending confirmation of performance metric feasibility captured elsewhere

**Comment by edasmalchi** [comment]
tracked in #899
