### ISSUE TITLE
Research Task - redeploy August speedmaps

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#851]
Since Muni dropped off for a couple days (unfortunately on our august `rt_date`), rebuild site with 8/23 data via `open_data` `make download_vehicle_positions_one_day`. Add second August date to `rt_dates`.

See: https://github.com/cal-itp/data-infra/issues/2921

**Comment by tiffanychu90** [comment]
@edasmalchi : i downloaded 8/15 date, paired with the scheduled data for that day, if you're interested
