### ISSUE TITLE
Research Task - Local Transit Projects List

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#890]
## Research Task

Make our master capital list from all the LRTPs present. Start working on a local (transit) projects list, perhaps by reaching out to people like Jeff Tumlin?

**Comment by edasmalchi** [comment]
Amanda to start from LRTP lists, Christian to shadow/ask more detailed transit priority questions. "Across CA, how much would we save with transit priority implementation?"

Connected to Julian (student assistant) scope (analyze benefits from list)

**Comment by amandaha8** [comment]
- [Google doc with all the LRTP](https://docs.google.com/spreadsheets/d/1A3i3yy_3LQKv8kRKqiWR9epF2gizHe5ebCRsczGFCjs/edit#gid=0)
- [File with all of the functions to clean LRTP projects](https://github.com/cal-itp/data-analyses/blob/main/project_list/_lrtp_utils.py)
- [Notebook that previews all the projects for each LRTP](https://github.com/cal-itp/data-analyses/blob/main/project_list/add_LRTP_congestion.ipynb)
- [Some of the lost work here](https://github.com/cal-itp/data-analyses/blob/main/project_list/_lost_utils.py) and [here](https://github.com/cal-itp/data-analyses/blob/main/project_list/add_LOST.ipynb), although a lot was manually moved over to Excel.
- [GCS bucket with LOST and LRTP](https://console.cloud.google.com/storage/browser/calitp-analytics-data/data-analyses/project_list?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=cal-itp-data-infra&prefix=&forceOnObjectsSortingFiltering=false) but [this is the file](https://console.cloud.google.com/storage/browser/_details/calitp-analytics-data/data-analyses/project_list/LRTP/all_LRTP_LOST.xlsx;tab=live_object?project=cal-itp-data-infra) with all the LRTP/LOST projects added.

**Comment by csuyat-dot** [comment]
Received more clarification. Starting with MPOs LRTP,  identify projects that improve existing transit performance (upgrading something, improve ridership, etc). Then compare this short list to the remaining projects in LRTP (% of..., cost vs...). May need to look at previous LRTPs to see if same projects were mentioned previously to see if projects were completed or not.

**Comment by tiffanychu90** [comment]
* 3 phases of projects: planned / partially funded / funded & under construction
   * state rail plan (planned)
   * TIRCP, LP2000 (partially funded)
   * LRTP (under construction)
* How to frame the discussion on how to prioritize which projects to actually build first

**Comment by edasmalchi** [comment]
Ideally we'd have a preliminary list by Jan 26

**Comment by csuyat-dot** [comment]
work continued on other PRs. closing issue
- #1000 
- #1034
