### ISSUE TITLE
Research Task - Transit Service Density

### ISSUE THREAD

**Issue by natam1** [cal-itp/data-analyses#896]
## Research Task

Where is service most dense? Using GTFS data, either trips or stops, we can identify the areas with the most service. 

* **Relevant PR** (if applicable):  

* **Question or Goal**: overarching goal of this issue  

* **Data Required**:
  * Currently have:
  * Need:  

* **Research Required**:  

* **Metrics**: what specific calculations are you looking to find?  

* **Expected Outputs / Findings**: what do you hope to have created when this is complete?

**Comment by tiffanychu90** [comment]
* census tract or block or travel analysis zone

**Comment by edasmalchi** [comment]
Would help to have progress on other metrics/geographies before figuring out this one, census tracts are probably not the right geography...

**Comment by KatrinaMKaiser** [comment]
Duplicative of #1091
