### ISSUE TITLE
Research Request - Measuring Accessibility

### ISSUE THREAD

**Issue by natam1** [cal-itp/data-analyses#898]
## Research Question
**Single sentence** description:  What should the target ratio be for accessibility? 
  
**Detailed** description:
Create a target ratio for accessibility. Ex: what percent of the regions' jobs are accessible? What is the ratio of accessibility?

Report by RTPA, ratio of jobs accessible via auto vs jobs accessible via transit. Accessibility ratio by RTPA would be useful.

## Stakeholders & End-Users
Who is asking the question, and who is the audience?

## Metrics
* any specific calculations
* you think will be needed

## Data sources
* **Cal-ITP data sources**:

* **External data sources**:

* **Remaining data source questions**:

## Deliverables:
Notebook, dashboard, narrative, presentation details.

## Timeline of deliverables:
Estimated completion date

**Comment by tiffanychu90** [comment]
* How many jobs are accessible via transit vs auto within 1 hr commute per RTPA / county (1 RTPA per county?)...report as ratio.
* Ridership numbers, focus on where this is large
* Accountability metric: some counties have no unmet transit needs, which means they can spend FTA money on roads. Figure out what this baseline ratio is (is it 1/10?)
