### ISSUE TITLE
Research Request - RT v Scheduled Exploratory 

### ISSUE THREAD

**Issue by amandaha8** [cal-itp/data-analyses#968]
## Research Question
**Single sentence** description:  
* After completing #936,  wrap up the findings through visuals/GH page/portfolio/other. 
* Relates to #824. 
**Detailed** description:

## How will this research be used?
Understand trips/routes/operators over time looking at real time versus scheduled data. 

## Stakeholders & End-Users
Operators, Caltrans employees, etc.

## Metrics
* TBD 

## Data sources
* Results from here: calitp-analytics-data/data-analyses/rt_vs_schedule/trip_level_metrics

## Deliverables
* Notebook
* Scripts

## Timeline of deliverables
TBD

**Comment by tiffanychu90** [comment]
* Closing...this is all wrapped up and included in #1079
